const express=require("express"),DB=require("better-sqlite3"),bcrypt=require("bcryptjs"),session=require("express-session"),path=require("path");
const app=express(),db=new DB("ubt.db");
db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY,name TEXT,class_name TEXT,username TEXT UNIQUE,password_hash TEXT,role TEXT DEFAULT 'student');
CREATE TABLE IF NOT EXISTS attempts(id INTEGER PRIMARY KEY,user_id INTEGER,score INTEGER,total INTEGER,percent INTEGER,created_at TEXT DEFAULT CURRENT_TIMESTAMP);`);
try{db.prepare("ALTER TABLE attempts ADD COLUMN topic TEXT DEFAULT 'Жалпы тест'").run()}catch(e){}
if(!db.prepare("SELECT 1 FROM users WHERE username='teacher'").get())db.prepare("INSERT INTO users(name,class_name,username,password_hash,role) VALUES(?,?,?,?,?)").run("Информатика мұғалімі","Мұғалім","teacher",bcrypt.hashSync("Teacher123!",10),"teacher");
app.use(express.json());app.use(session({secret:process.env.SESSION_SECRET||"change-me",resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:"lax",maxAge:43200000}}));app.use(express.static(path.join(__dirname,"public")));
const auth=(q,s,n)=>q.session.user?n():s.status(401).json({error:"Жүйеге кіріңіз"}),teach=(q,s,n)=>q.session.user?.role==="teacher"?n():s.status(403).json({error:"Мұғалімге ғана қолжетімді"});
app.post("/api/register",(q,s)=>{let{name,className,username,password}=q.body;if(!name||!className||!username||!password||password.length<6)return s.status(400).json({error:"Барлық жолды толтырыңыз. Құпиясөз кемінде 6 таңба."});try{let x=db.prepare("INSERT INTO users(name,class_name,username,password_hash) VALUES(?,?,?,?)").run(name.trim(),className.trim(),username.trim().toLowerCase(),bcrypt.hashSync(password,10));q.session.user={id:x.lastInsertRowid,name:name.trim(),className:className.trim(),username:username.trim().toLowerCase(),role:"student"};s.json(q.session.user)}catch(e){s.status(400).json({error:"Бұл логин бұрын тіркелген."})}});
app.post("/api/login",(q,s)=>{let u=db.prepare("SELECT * FROM users WHERE username=?").get((q.body.username||"").trim().toLowerCase());if(!u||!bcrypt.compareSync(q.body.password||"",u.password_hash))return s.status(401).json({error:"Логин немесе құпиясөз қате."});q.session.user={id:u.id,name:u.name,className:u.class_name,username:u.username,role:u.role};s.json(q.session.user)});
app.post("/api/logout",(q,s)=>q.session.destroy(()=>s.json({ok:true})));app.get("/api/me",(q,s)=>s.json(q.session.user||null));
app.post("/api/attempts",auth,(q,s)=>{if(q.session.user.role!=="student")return s.status(400).json({error:"Оқушыға арналған"});let total=Math.max(1,+q.body.total||1),score=Math.max(0,Math.min(total,+q.body.score||0)),topic=(q.body.topic||"Жалпы тест").slice(0,100),percent=Math.round(score/total*100);db.prepare("INSERT INTO attempts(user_id,score,total,percent,topic) VALUES(?,?,?,?,?)").run(q.session.user.id,score,total,percent,topic);s.json({ok:true})});
app.get("/api/my",auth,(q,s)=>s.json(db.prepare("SELECT topic,score,total,percent,created_at FROM attempts WHERE user_id=? ORDER BY id DESC").all(q.session.user.id)));
app.get("/api/rank",(q,s)=>s.json(db.prepare(`SELECT u.name,u.class_name className,ROUND(AVG(a.percent)) average,MAX(a.percent) best,COUNT(a.id) attempts FROM users u JOIN attempts a ON u.id=a.user_id WHERE u.role='student' GROUP BY u.id ORDER BY average DESC,best DESC,attempts DESC,u.name`).all()));
app.get("/api/teacher",teach,(q,s)=>s.json({students:db.prepare(`SELECT u.name,u.class_name className,u.username,COUNT(a.id) attempts,COALESCE(MAX(a.percent),0) best,COALESCE(ROUND(AVG(a.percent)),0) average FROM users u LEFT JOIN attempts a ON u.id=a.user_id WHERE u.role='student' GROUP BY u.id ORDER BY u.class_name,u.name`).all(),attempts:db.prepare(`SELECT u.name,u.class_name className,a.topic,a.score,a.total,a.percent,a.created_at FROM attempts a JOIN users u ON u.id=a.user_id ORDER BY a.id DESC LIMIT 500`).all()}));
app.listen(process.env.PORT||3000,()=>console.log("Informatika UBT v3 live"));